#!/usr/bin/python

"""Specify an image name on the command line to print that image.
Otherwise, one of the installed images is randomly chosen."""

import os
import sys
import random

images_dir = "ascii_images"

images = os.listdir(images_dir)

if len(sys.argv) > 1 and sys.argv[1] in images:
    fname = sys.argv[1]
else:
    fname = random.choice(images)

with open(os.path.join(images_dir, fname)) as f:
    print(f.read())
